version: "2"
services:
 
  webapp:
    links:
      - mongo
    image: leanote:1.0
    #restart: always
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "./conf/app.conf:/go/src/github.com/leanote/leanote/conf/app.conf"
      - "/var/log:/var/log"
      - "./files:/go/src/github.com/leanote/leanote/files"
      - "./upload:/go/src/github.com/leanote/leanote/public/upload"

  mongo:
    image: mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "/opt/mongo/db:/data/db"
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
 
